apiVersion: apps/v1
kind: Deployment
metadata:
  name: tqhuy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tqhuy-app
  template:
    metadata:
      labels:
        app: tqhuy-app
    spec:
      containers:
        - name: my-fw-cont
          image: tqhuy1996developer/istock
          ports:
            - containerPort: 80
              name: web
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "75Mi"
              cpu: "75m"